install.packages("RPMM")
install.packages("ggplot2")
install.packages("dplyr")
install.packages("BiocManager")
install.packages("devtools")
if (!requireNamespace("BiocManager", quietly = TRUE))
  install.packages("BiocManager")
BiocManager::install("minfi", version = "3.8")
if (!requireNamespace("BiocManager", quietly = TRUE))
  install.packages("BiocManager")
BiocManager::install("minfiData", version = "3.8")
source("https://bioconductor.org/biocLite.R")
biocLite("FlowSorted.CordBlood.450k")
biocLite("SummarizedExperiment")
library(devtools)
#install_github("Bioconductor-mirror/sva")
if (!requireNamespace("BiocManager", quietly = TRUE))
  install.packages("BiocManager")
BiocManager::install("sva", version = "3.8")

biocLite("IlluminaHumanMethylationEPICanno.ilm10b3.hg19")
